const fs = require('fs');

// All bottles sorted A-Z by name, with data from Absolutpedia
const bottles = [
  // STANDARD & FLAVOURS
  { name: "Absolut 100 (2022 Design)", filter: "Standard & Flavours", since: 2022, distribution: "Worldwide", numberOfBottles: "Core release", designer: "", description: "2022 version of Absolut 100. Black bottle with 50% alc./vol. 100 proof vodka.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2022/08/100_21.jpg" },
  { name: "Absolut Amber", filter: "Limited Edition", since: 2013, distribution: "Worldwide in DFS", numberOfBottles: "200 000", designer: "", description: "Absolut Amber is a limited edition oak-aged vodka with a warm amber color and smooth, rich taste. Aged in oak barrels, it offers notes of vanilla, caramel and dried fruit.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/amber.jpg" },
  { name: "Absolut Be The Thunder", filter: "Second Skin", since: 2019, distribution: "Worldwide", numberOfBottles: "Unknown", designer: "", description: "A metallic silver second skin with lightning bolt design, released as a limited edition.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/bethethunder.jpg" },
  { name: "Absolut Beirut Bag", filter: "Paper Wrap", since: 2019, distribution: "Lebanon", numberOfBottles: "Unknown", designer: "", description: "Paper wrap edition featuring Beirut city design.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/beirut.jpg" },
  { name: "Absolut Berlin", filter: "International Cities & Countries", since: 2014, distribution: "Germany, Austria, Switzerland", numberOfBottles: "300 000", designer: "Zhivago Duncan", description: "The Fernsehturm TV tower, a relic of a once divided city, stands over the city of Berlin. In the nearly 25 years since East and West Berlin unified, this icon which once represented a controlled message of a dismantled government, now stands for a city defined by artistic freedom and creative discovery.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/berlin.jpg" },
  { name: "Absolut Blank #1 (Mario Wagner)", filter: "Limited Edition", since: 2011, distribution: "Worldwide", numberOfBottles: "Unknown", designer: "Mario Wagner", description: "Absolut Blank Edition #1 by Mario Wagner. Part of the Absolut Blank campaign where artists were given a blank Absolut bottle as their canvas.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/blank1.jpg" },
  { name: "Absolut Blank #2 (Dave Kinsey)", filter: "Limited Edition", since: 2013, distribution: "Europe", numberOfBottles: "Unknown", designer: "Dave Kinsey", description: "Absolut Vodka Blank Edition by Dave Kinsey features an explosion of bright colors and darker-hued washes that reveal Kinsey's roots as a street artist while highlighting his extraordinary fine art skill.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/blank2.jpg" },
  { name: "Absolut Blank #3 (Woodkid)", filter: "Limited Edition", since: 2013, distribution: "Europe", numberOfBottles: "Unknown", designer: "Woodkid", description: "Absolut Blank Edition #3 by Woodkid (Yoann Lemoine). A black and white design featuring intricate illustrations.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/blank3.jpg" },
  { name: "Absolut Blue Label (2015 Design)", filter: "Standard & Flavours", since: 2015, distribution: "Worldwide", numberOfBottles: "Core release", designer: "The Brand Union / Luca Barcellona", description: "Last rebranding in 2015 was curated by The Brand Union agency. Calligrapher Luca Barcellona has created a new script for the bottle, which is inspired by Swedish lettering but is also cool, simple and modern. Illustrator and engraver Martin Mörck has redrawn the seal on the bottle depicting a portrait of Absolut founder Lars Olsson Smith.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/absolut-blue-label-2015-1.jpg" },
  { name: "Absolut Blue Label (2021 Design)", filter: "Standard & Flavours", since: 2021, distribution: "Worldwide", numberOfBottles: "Core release", designer: "", description: "Minimal and clear restyling of the iconic Absolut Vodka bottle. After more than 50 years the text on the bottle is replaced with handwritten \"Swedish vodka\". \"Country of Sweden\" is engraved on the bottle and a label shows the information and L.O. Smith signature. In the backside there is the illustration of Åhus village.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/absolut-blue-label-2021-1.jpg" },
  { name: "Absolut Brooklyn", filter: "Limited Edition", since: 2010, distribution: "USA", numberOfBottles: "225 000", designer: "Spike Lee", description: "Designed in collaboration with Spike Lee, the bottle is a colorful depiction of the stoop where the Brooklyn-bred auteur grew up – #165. Harkening back to the decades-long notion that the stoop is truly the epicenter of creativity, culture and community.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/absolut_brooklyn.jpg" },
  { name: "Absolut Buenos Aires", filter: "International Cities & Countries", since: 2016, distribution: "Argentina", numberOfBottles: "69 300", designer: "Gaspar Libedinsky", description: "The Obelisk is the silent witness to the diversity that surrounds and characterizes Buenos Aires. This limited edition bottle's illustration is an interpretation of the perspective one obtains from the monument itself, a window onto the world of the Cocktail City.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/buenos-aires.jpg" },
  { name: "Absolut Canada", filter: "International Cities & Countries", since: 2017, distribution: "Canada", numberOfBottles: "Unknown", designer: "", description: "Limited edition celebrating Canada, featuring iconic Canadian imagery on the bottle design.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/canada.jpg" },
  { name: "Absolut Carnaval Rio de Janeiro", filter: "Second Skin", since: 2014, distribution: "Brazil", numberOfBottles: "Unknown", designer: "", description: "Second skin edition celebrating Rio de Janeiro's famous Carnival.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/carnaval-rio.jpg" },
  { name: "Absolut Carnaval São João", filter: "Second Skin", since: 2014, distribution: "Brazil", numberOfBottles: "Unknown", designer: "", description: "Second skin edition celebrating the São João festival in Brazil.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/carnaval-sao-joao.jpg" },
  { name: "Absolut Carnaval São Paulo", filter: "Second Skin", since: 2014, distribution: "Brazil", numberOfBottles: "Unknown", designer: "", description: "Second skin edition celebrating São Paulo's Carnival.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/carnaval-sao-paulo.jpg" },
  { name: "Absolut Cherrys (2016 Design)", filter: "Standard & Flavours", since: 2016, distribution: "Worldwide", numberOfBottles: "Core release", designer: "", description: "Absolut Cherrys is made from all-natural cherry flavors. Rich and smooth with a fruity character of ripe cherries.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/12/cherrys1.jpg" },
  { name: "Absolut Chicago", filter: "Limited Edition", since: 2013, distribution: "USA", numberOfBottles: "270 000", designer: "Threadless", description: "Capturing the essence of the city's thriving culinary scene, Absolut Chicago features a savory blend of olive and rosemary and a bottle that showcases the iconic cityscape, stemmed from a collaboration with Chicago's own Threadless design community.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/chicago.jpg" },
  { name: "Absolut Choir Bag", filter: "Paper Wrap", since: 2019, distribution: "Unknown", numberOfBottles: "Unknown", designer: "", description: "Paper wrap edition with choir/music themed design.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/choir.jpg" },
  { name: "Absolut Cilantro", filter: "Standard & Flavours", since: 2013, distribution: "Worldwide", numberOfBottles: "Core release", designer: "", description: "Absolut Cilantro is a contemporary flavored vodka alive with aromatic cilantro and vibrant lime. Taking its inspiration from Latin American kitchens, it bursts onto the scene with a taste that's smooth, fresh and unforgettable.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/12/cilantro-1.jpg" },
  { name: "Absolut Citron (2021 Design)", filter: "Standard & Flavours", since: 2021, distribution: "Worldwide", numberOfBottles: "Core release", designer: "", description: "2021 version of Absolut Citron. Lemon-flavored vodka with the new minimal bottle design.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/02/absolut-citron-2022.jpg" },
  { name: "Absolut Denim", filter: "Second Skin", since: 2013, distribution: "Worldwide", numberOfBottles: "Unknown", designer: "", description: "A denim-wrapped second skin edition. The bottle is covered in a denim fabric sleeve.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/denim.jpg" },
  { name: "Absolut Dubai Bag", filter: "Paper Wrap", since: 2019, distribution: "United Arab Emirates", numberOfBottles: "Unknown", designer: "Randy Constantino", description: "Medium blue bag depicting the city skyline with a bright orange sun rising above it.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/dubai.jpg" },
  { name: "Absolut Elyx #1", filter: "Elyx", since: 2010, distribution: "Worldwide", numberOfBottles: "Core release", designer: "", description: "Premium line of Absolut Vodka crafted from hand-selected estate wheat, and blended with soft and naturally filtered water. It is a small-batch vodka, produced according to craft techniques, in an authentic 1929 copper rectification still.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2022/08/elyx1.jpg" },
  { name: "Absolut Elyx #2", filter: "Elyx", since: 2013, distribution: "Worldwide", numberOfBottles: "Core release", designer: "", description: "Second design iteration of Absolut Elyx premium vodka. Manually distilled in a 1921 copper rectification still known as Column 51.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2022/08/elyx2.jpg" },
  { name: "Absolut Elyx #3", filter: "Elyx", since: 2018, distribution: "Worldwide", numberOfBottles: "Core release", designer: "", description: "Third design iteration of Absolut Elyx. The silky textured vodka is a result of the single estate wheat, the manual operation and the old copper catalyzation process.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2022/08/elyx3.jpg" },
  { name: "Absolut Elyx #4", filter: "Elyx", since: 2021, distribution: "Worldwide", numberOfBottles: "Core release", designer: "", description: "Fourth and latest design of Absolut Elyx premium vodka. Copper naturally catalyzes trace compounds in the spirit, purifying the vodka and adding a highly prized silky texture and taste.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2022/08/elyx4.jpg" },
  { name: "Absolut Exposure #1", filter: "Limited Edition", since: 2013, distribution: "Worldwide in DFS", numberOfBottles: "100 000", designer: "Johan Renck", description: "A unique Traveler's Exclusive limited edition flavour celebrating the arts of photography and illusion, in creative collaboration with visionary artist Johan Renck. Crafted with honey melon and lemongrass.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/exposure1.jpg" },
  { name: "Absolut Exposure #2", filter: "Limited Edition", since: 2013, distribution: "Worldwide in DFS", numberOfBottles: "100 000", designer: "Johan Renck", description: "Second bottle in the Exposure series. Swedish artist Johan Renck photographed actress and supermodel Lydia Hearst guised in different personas.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/exposure2.jpg" },
  { name: "Absolut Exposure #3", filter: "Limited Edition", since: 2013, distribution: "Worldwide in DFS", numberOfBottles: "100 000", designer: "Johan Renck", description: "Third bottle in the Exposure series. Innovative and groundbreaking design incorporating photographs in bottle printing.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/exposure3.jpg" },
  { name: "Absolut Flavor Of The Tropics", filter: "Limited Edition", since: 2009, distribution: "Worldwide in DFS", numberOfBottles: "300 000", designer: "Williams Murray Hamm", description: "Mango, Orange, Lychee, Pineapple and Melon flavored vodka. The first limited-edition flavour from Absolut to be launched exclusively in the global travel retail sector.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/tropics.jpg" },
  { name: "Absolut Glimmer", filter: "Limited Edition", since: 2010, distribution: "Worldwide", numberOfBottles: "4 000 000", designer: "", description: "The Glimmer is the 2010 end-of-the-year edition. A shimmering bottle with a metallic finish that catches the light.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/glimmer.jpg" },
  { name: "Absolut Gräpe (2017 Design)", filter: "Standard & Flavours", since: 2017, distribution: "Worldwide", numberOfBottles: "Core release", designer: "", description: "Absolut Gräpe is incredibly easy to mix and is made from all-natural ingredients and contains no sugar. The combination of white grape, dragon fruit and papaya makes it multi-dimensional.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/12/grape1.jpg" },
  { name: "Absolut Greensaver", filter: "Limited Edition", since: 2008, distribution: "Greece", numberOfBottles: "Unknown", designer: "Konstantinos Vita", description: "Colorful bottle specially designed to remind of the protection of the environment.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/greensaver-1.jpg" },
  { name: "Absolut Illusion", filter: "Limited Edition", since: 2013, distribution: "Worldwide in DFS", numberOfBottles: "Unknown", designer: "", description: "A limited edition travel retail exclusive with an optical illusion design on the bottle.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/illusion.jpg" },
  { name: "Absolut India #1", filter: "International Cities & Countries", since: 2016, distribution: "India", numberOfBottles: "Unknown", designer: "", description: "First limited edition celebrating India, featuring colorful Indian-inspired artwork.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/india1.jpg" },
  { name: "Absolut India #2", filter: "International Cities & Countries", since: 2018, distribution: "India", numberOfBottles: "103 000", designer: "Ajay Boga", description: "India is now the home of 70 percent of the world's tiger population. Ajay Boga's motif was inspired by the strength and the courage of a tiger, with various Indian patterns and elements highlighting the diversity, culture, energy and pride that the nation holds.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/india2.jpg" },
  { name: "Absolut Istanbul", filter: "International Cities & Countries", since: 2012, distribution: "Turkey", numberOfBottles: "180 000", designer: "Yigit Yazici", description: "Collaboration between the trendy vodka label and Turkish Artist Yigit Yazici. Absolut Istanbul pays tribute to the city's iconic emblems, Galata Tower and the Bosphorus in vibrant colours.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/istanbul.jpg" },
  { name: "Absolut Istanbul Bag", filter: "Paper Wrap", since: 2012, distribution: "Turkey", numberOfBottles: "Unknown", designer: "", description: "Paper wrap edition featuring Istanbul city design.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/istanbul-bag.jpg" },
  { name: "Absolut Juice Apple Edition", filter: "Premixed", since: 2018, distribution: "UK", numberOfBottles: "Core release", designer: "", description: "Flavored fruit juice 35% abv. Contains natural ingredients with a paper label suggesting it is an autumn flavor.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/12/apple500.jpg" },
  { name: "Absolut Juice Strawberry Edition", filter: "Premixed", since: 2018, distribution: "UK", numberOfBottles: "Core release", designer: "", description: "Flavored fruit juice 35% abv. Contains natural ingredients and has a paper label.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/12/strawberry500.jpg" },
  { name: "Absolut Karnival", filter: "Limited Edition", since: 2014, distribution: "Worldwide", numberOfBottles: "140 000", designer: "Rafael Grampá", description: "Absolut Carnival is a passion fruit and orange blossom-flavored limited edition capturing the transformative energy of Carnival. Features artwork by the Brazilian graphic novel artist and writer Rafael Grampá.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/karnival1000.jpg" },
  { name: "Absolut Korea", filter: "International Cities & Countries", since: 2016, distribution: "Korea", numberOfBottles: "186 000", designer: "Heo Wook", description: "A coffee, almond and chili flavored limited edition capturing the essence of Korean traditions with a modern twist. Created in collaboration with contemporary Korean artist, Heo Wook.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/korea.jpg" },
  { name: "Absolut Lollapalooza #1 Bag", filter: "Paper Wrap", since: 2018, distribution: "Various", numberOfBottles: "Unknown", designer: "", description: "First paper wrap edition for the Lollapalooza music festival.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/lollapalooza1.jpg" },
  { name: "Absolut Lollapalooza #2 Bag", filter: "Paper Wrap", since: 2019, distribution: "Various", numberOfBottles: "Unknown", designer: "", description: "Second paper wrap edition for the Lollapalooza music festival.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/lollapalooza2.jpg" },
  { name: "Absolut London", filter: "International Cities & Countries", since: 2012, distribution: "UK", numberOfBottles: "250 000", designer: "Jamie Hewlett", description: "Designed by Jamie Hewlett, co-creator of Gorillaz. The bottle features a vibrant London cityscape.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/london.jpg" },
  { name: "Absolut Mandrin (2021 Design)", filter: "Standard & Flavours", since: 2021, distribution: "Worldwide", numberOfBottles: "Core release", designer: "", description: "2021 version of Absolut Mandrin. Orange and mandarin flavored vodka with the new minimal bottle design.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2022/08/mandrin2022.jpg" },
  { name: "Absolut Masquerade", filter: "Second Skin", since: 2008, distribution: "Worldwide", numberOfBottles: "3 100 000", designer: "", description: "The Masquerade skin is the 2008 end-of-the-year edition. Shiny red skin containing a regular blue bottle. Made from soft and shiny red spangles, with a zipper on the back. Built of exactly 3,238 shiny red spangles.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/masquerade.jpg" },
  { name: "Absolut Mexico", filter: "International Cities & Countries", since: 2012, distribution: "Mexico & USA", numberOfBottles: "235 000", designer: "Dr. Lakra", description: "Dr Lakra, alias of Jeronimo Lopez Ramirez, has collaborated with Absolut to pay homage to Mexican culture and the country's multicultural heritage, featuring icons from ancient Mayan culture.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/mexico.jpg" },
  { name: "Absolut Miami", filter: "Limited Edition", since: 2012, distribution: "USA", numberOfBottles: "141 000", designer: "", description: "The bottle is styled with sunshine, palm trees and waves as a show of what Miami is known for. Passion fruit flavored.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/miami.jpg" },
  { name: "Absolut Mini Bar", filter: "Second Skin", since: 2010, distribution: "Worldwide", numberOfBottles: "Unknown", designer: "", description: "A second skin edition designed to look like a minibar. Creative packaging concept.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/minibar.jpg" },
  { name: "Absolut Mode", filter: "Limited Edition", since: 2009, distribution: "Worldwide in DFS", numberOfBottles: "Unknown", designer: "", description: "A fashion-inspired limited edition travel retail exclusive.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/mode.jpg" },
  { name: "Absolut New Zealand", filter: "Second Skin", since: 2012, distribution: "New Zealand", numberOfBottles: "Unknown", designer: "", description: "Second skin edition celebrating New Zealand with Maori-inspired design elements.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/new-zealand.jpg" },
  { name: "Absolut No Label", filter: "Limited Edition", since: 2009, distribution: "Worldwide", numberOfBottles: "Unknown", designer: "", description: "In An ABSOLUT World, there Are No Labels. A bold and innovative project where the brand challenges labels and prejudice about sexual identities. A limited edition naked Absolut bottle, with no label and no logo.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/no_label.jpg" },
  { name: "Absolut Orient Apple", filter: "Standard & Flavours", since: 2011, distribution: "Worldwide", numberOfBottles: "Core release", designer: "", description: "Absolut Orient Apple is made exclusively from natural ingredients. Fresh and fruity with a distinct character of ripe red apples with a slight note of ginger.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/12/orient-apple.jpg" },
  { name: "Absolut Originality", filter: "Limited Edition", since: 2013, distribution: "Worldwide", numberOfBottles: "4 000 000", designer: "", description: "Taking inspiration from traditional Swedish glass crafts, every bottle has a drop of cobalt blue infused into its glass. Added just as the molten glass goes into the mould at 1100°C, the drop of cobalt blue streams down inside the glass creating a unique streak of blue.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/originality.jpg" },
  { name: "Absolut Oz", filter: "International Cities & Countries", since: 2012, distribution: "Australia", numberOfBottles: "45 000", designer: "Baz Luhrmann", description: "A limited edition Australian collaboration with Baz Luhrmann, Australia's most successful creative outside of the music industry.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/oz.jpg" },
  { name: "Absolut Polakom", filter: "International Cities & Countries", since: 2011, distribution: "Poland", numberOfBottles: "Unknown", designer: "", description: "Limited edition celebrating Poland and Polish culture.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/polakom.jpg" },
  { name: "Absolut Red Label", filter: "Standard & Flavours", since: 1979, distribution: "Worldwide", numberOfBottles: "Discontinued (2006)", designer: "", description: "Red Label, with 50% alc./vol. 100% proof. Launched in 1979, discontinued in 2006 and replaced with Absolut 100.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/absolut-red-label-2.jpg" },
  { name: "Absolut Rio", filter: "International Cities & Countries", since: 2013, distribution: "Brazil", numberOfBottles: "Unknown", designer: "", description: "Limited edition celebrating Rio de Janeiro, featuring colorful Brazilian-inspired artwork.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/rio.jpg" },
  { name: "Absolut Rock", filter: "Second Skin", since: 2009, distribution: "Worldwide", numberOfBottles: "3 600 000", designer: "", description: "The Rock skin is the 2009 end-of-the-year edition. A black leather limited edition second skin, with metal spikes, containing a regular blue bottle.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/rock.jpg" },
  { name: "Absolut Ruby Red (2016 Design)", filter: "Standard & Flavours", since: 2016, distribution: "Worldwide", numberOfBottles: "Core release", designer: "", description: "Absolut Ruby Red is smooth and fruity with a crisp and refreshing character of zesty grapefruit. Made exclusively from natural ingredients with no added sugar.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/12/ruby-red1.jpg" },
  { name: "Absolut San Francisco", filter: "Limited Edition", since: 2012, distribution: "USA", numberOfBottles: "Unknown", designer: "", description: "Limited edition celebrating San Francisco, featuring the city's iconic imagery.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/san-francisco.jpg" },
  { name: "Absolut Selfridge", filter: "Second Skin", since: 2009, distribution: "UK", numberOfBottles: "5 000", designer: "Peter Jensen", description: "Limited edition skin released to celebrate the centenary of the English shop Selfridges.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/11/selfridge.jpg" },
  { name: "Absolut Sequin", filter: "Second Skin", since: 2018, distribution: "Worldwide", numberOfBottles: "Unknown", designer: "", description: "A sequin-covered second skin edition that shimmers and changes appearance when touched.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/sequin.jpg" },
  { name: "Absolut 72 Bian 变", filter: "Limited Edition", since: 2010, distribution: "China, Singapore & Malaysia", numberOfBottles: "350 000", designer: "Gao Yu", description: "Inspired by an ancient Chinese fable, \"Journey to the West,\" a heroic story about the monkey king Sun Wukong, who acquires the power to undergo 72 transformations (or 72 bian).", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2024/08/bian.jpg" },
  { name: "Absolut Soy Capaz De", filter: "Limited Edition", since: 2014, distribution: "Colombia", numberOfBottles: "1 000", designer: "", description: "Colombian limited edition bottle. A regular blue label 750ml, with a white plastic foil on it. Limited to approximately 1000 copies.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/soy_capaz.jpg" },
  { name: "Absolut Svea", filter: "International Cities & Countries", since: 2018, distribution: "Sweden", numberOfBottles: "Unknown", designer: "", description: "Limited edition celebrating Sweden, named after the national personification of Sweden.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/svea.jpg" },
  { name: "Absolut Texas", filter: "Limited Edition", since: 2014, distribution: "USA", numberOfBottles: "Unknown", designer: "Cruz Ortiz", description: "Absolut vodka with cucumber and Serrano chili flavor. The taste is rich and smooth with notes of fresh cucumber, and a warm spicy character; a flavor inspired by Southwestern cuisine.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/texas.jpg" },
  { name: "Absolut Tomorrowland Bag", filter: "Paper Wrap", since: 2019, distribution: "Belgium, Netherlands", numberOfBottles: "35 000", designer: "", description: "Pink/Rose bag bottom to Blue top enhanced by butterflies. Issued for the Tomorrowland music festival.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/tomorrowland.jpg" },
  { name: "Absolut Unique", filter: "Limited Edition", since: 2012, distribution: "Worldwide", numberOfBottles: "3 980 000", designer: "", description: "The Unique is the 2012 end-of-the-year edition. Every bottle in the range is 'unique' – each has a numbered label and the same bottle shape, but painted with different colours and shapes making each one different.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/unique750.jpg" },
  { name: "Absolut America #1 - United", filter: "Limited Edition", since: 2016, distribution: "USA", numberOfBottles: "Unknown", designer: "", description: "Designed in red and white stripes and blue rectangle resembling the American Flag. The bottle represents unity.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/america.jpg" },
  { name: "Absolut Warhol", filter: "Limited Edition", since: 2014, distribution: "Worldwide", numberOfBottles: "4 000 000", designer: "Andy Warhol (posthumous)", description: "Inspired by Andy Warhol's original 1986 painting of the Absolut bottle. The design features Warhol's iconic pop art style with bold colors and graphic elements.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/warhol.jpg" },
  { name: "Absolut Watkins", filter: "Limited Edition", since: 2011, distribution: "Worldwide in DFS", numberOfBottles: "500 000", designer: "Liselotte Watkins", description: "Rich, smooth and sensual in taste with the distinct qualities of freshly ground coffee with notes of almond, caramel and warm chilli. Bottle decor created by celebrated Swedish fashion illustrator Liselotte Watkins.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/watkins.jpg" },
  { name: "Absolut Wild Tea", filter: "Standard & Flavours", since: 2010, distribution: "Worldwide", numberOfBottles: "Core release", designer: "", description: "Absolut Wild Tea is a blend of vodka with elderflower and black tea flavors. A unique and refreshing taste experience.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/12/wild-tea.jpg" },
  { name: "Absolut Åhus", filter: "International Cities & Countries", since: 2019, distribution: "Sweden", numberOfBottles: "Unknown", designer: "", description: "Limited edition celebrating Åhus, the birthplace of Absolut Vodka in southern Sweden.", frontPhoto: "https://absolutpedia.com/wp-content/uploads/2020/01/ahus.jpg" },
];

// Sort A-Z by name
bottles.sort((a, b) => a.name.localeCompare(b.name));

// Build the JS file content
let output = 'const bottleData = [\n';
bottles.forEach((b, i) => {
  const desc = b.description.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n');
  output += '    {\n';
  output += `        "name": "${b.name}",\n`;
  output += `        "filter": "${b.filter}",\n`;
  output += `        "since": ${typeof b.since === 'number' ? b.since : '"' + b.since + '"'},\n`;
  output += `        "distribution": "${b.distribution}",\n`;
  output += `        "numberOfBottles": "${b.numberOfBottles}",\n`;
  output += `        "designer": "${b.designer}",\n`;
  output += `        "description": "${desc}",\n`;
  output += `        "frontPhoto": "${b.frontPhoto}"\n`;
  output += '    }' + (i < bottles.length - 1 ? ',' : '') + '\n';
});
output += '];\n';

// Read the existing database.js to get the template/modal/render functions
const existing = fs.readFileSync('database.js', 'utf8');
const funcStart = existing.indexOf('function bottleTemplate');
const functions = existing.substring(funcStart);

output += '\n' + functions;

fs.writeFileSync('database.js', output, 'utf8');
console.log(`Generated database.js with ${bottles.length} bottles (sorted A-Z)`);

